apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: look-up
  name: look-up
spec:
  replicas: 1
  selector:
    matchLabels:
      app: look-up
  template:
    metadata:
      labels:
        app: look-up
    spec:
      containers:
        - name: look-up
          image: registry-db68de2808-uuctf.apps.ir-thr-ba1.arvancaas.ir/jahangirzad/look-up:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
            requests:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
