apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keep-alive
  name: keep-alive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keep-alive
  template:
    metadata:
      labels:
        app: keep-alive
    spec:
      containers:
        - name: keep-alive
          image: registry-db68de2808-uuctf.apps.ir-thr-ba1.arvancaas.ir/sajjad/keep-alive:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
            requests:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keep-alive
  name: keep-alive
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8888
  selector:
    app: keep-alive
