apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warmup
  name: warmup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warmup
  template:
    metadata:
      labels:
        app: warmup
    spec:
      containers:
        - name: warmup
          image: registry-db68de2808-uuctf.apps.ir-thr-ba1.arvancaas.ir/jahangirzad/warmup:1.0.0
          ports:
            - containerPort: 5002
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
            requests:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
      imagePullSecrets:
        - name: regcred

      restartPolicy: Always
