apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hard
  name: hard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hard
  template:
    metadata:
      labels:
        app: hard
    spec:
      containers:
        - name: hard
          image: registry-db68de2808-uuctf.apps.ir-thr-ba1.arvancaas.ir/jahangirzad/hard:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
            requests:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
