apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: karaball
  name: karaball
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karaball
  template:
    metadata:
      labels:
        app: karaball
    spec:
      containers:
        - name: karaball
          image: registry-db68de2808-uuctf.apps.ir-thr-ba1.arvancaas.ir/kourosh/karaball:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 15623
              protocol: TCP
          resources:
            limits:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
            requests:
              cpu: "250m"
              ephemeral-storage: 128Mi
              memory: 500Mi
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: karaball
  name: karaball
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 15623
  selector:
    app: karaball
