apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: flag-seller-app-claim0
  name: flag-seller-app-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
